<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project Euler Problem 2</title>
</head>
<body>
<h1>Project Euler Problem 2</h1>
<pre>
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
</pre>
<?php
/*
 * Fn = Fn-1 + Fn-2 =
 * Fn-2 + Fn-3 + Fn-3 + Fn-4 =
 * Fn-3 + Fn-4 + Fn-3 + Fn-3 +Fn-4 = 3Fn-3 + 2Fn-4 =
 * 3Fn-3 + Fn-4 + Fn-5 + Fn-6) =
 * 4Fn-3 + Fn-6
*/
$start = microtime(true);

$n1 = 1;
$n2 = 2;
$n3 = $n1 + $n2;
$sum = 2;
while ($n3 < 4000000) {
    $n1 = $n2;
    $n2 = $n3;
    $n3 = $n1 + $n2;

    if ($n3 % 2 == 0) {
        $sum += $n3;
    }
}

echo '<p>Result Using Brute Force: ' . $sum . '</p>';
$end = microtime(true);
echo $end - $start;

echo "<hr/>";
$start = microtime(true);
$fn3 = 2;
$fn6 = 0;
$sum = 2;
$result = 0;
while ($result < 4000000) {
    $sum += $result;
    $result = 4 * $fn3 + $fn6;
    $fn6 = $fn3;
    $fn3 = $result;
}
echo '<p>Result using a more efficient way: ' . $sum . '</p>';
$end = microtime(true);
echo $end - $start;
?>
</body>
</html>